# Qwen-2.5-3D-Instruct with different random seeds and tasks.
CUDA_VISIBLE_DEVICES=0 python examples/main_text.py --seed 0 --task biorxiv --gen_model_name Qwen/Qwen2.5-3B-Instruct --fine_tune_model_name Qwen/Qwen2.5-3B-Instruct --target_modules q_proj v_proj --use_local_model True --lr 3e-4 --variation_api_fold 1 --num_synthetic_per_iter 100 --num_iter 10 --priv_sampling_ratio 0.2 --max_completion_tokens 1024 --dp_epsilon 1.0 --dp_delta 1E-5 --train_batch_size 4 > temp_qwen_biorxiv_seed0.txt
CUDA_VISIBLE_DEVICES=0 python examples/main_text.py --seed 1 --task biorxiv --gen_model_name Qwen/Qwen2.5-3B-Instruct --fine_tune_model_name Qwen/Qwen2.5-3B-Instruct --target_modules q_proj v_proj --use_local_model True --lr 3e-4 --variation_api_fold 1 --num_synthetic_per_iter 100 --num_iter 10 --priv_sampling_ratio 0.2 --max_completion_tokens 1024 --dp_epsilon 1.0 --dp_delta 1E-5 --train_batch_size 4 > temp_qwen_biorxiv_seed1.txt
CUDA_VISIBLE_DEVICES=0 python examples/main_text.py --seed 42 --task biorxiv --gen_model_name Qwen/Qwen2.5-3B-Instruct --fine_tune_model_name Qwen/Qwen2.5-3B-Instruct --target_modules q_proj v_proj --use_local_model True --lr 3e-4 --variation_api_fold 1 --num_synthetic_per_iter 100 --num_iter 10 --priv_sampling_ratio 0.2 --max_completion_tokens 1024 --dp_epsilon 1.0 --dp_delta 1E-5 --train_batch_size 4 > temp_qwen_biorxiv_seed42.txt

CUDA_VISIBLE_DEVICES=0 python examples/main_text.py --seed 0 --task congressional --gen_model_name Qwen/Qwen2.5-3B-Instruct --fine_tune_model_name Qwen/Qwen2.5-3B-Instruct --target_modules q_proj v_proj --use_local_model True --lr 5e-4 --variation_api_fold 1 --num_synthetic_per_iter 100 --num_iter 10 --priv_sampling_ratio 0.2 --max_completion_tokens 1024 --dp_epsilon 1.0 --dp_delta 1E-5 --train_batch_size 4 > temp_qwen_congressional_seed0.txt
CUDA_VISIBLE_DEVICES=0 python examples/main_text.py --seed 1 --task congressional --gen_model_name Qwen/Qwen2.5-3B-Instruct --fine_tune_model_name Qwen/Qwen2.5-3B-Instruct --target_modules q_proj v_proj --use_local_model True --lr 5e-4 --variation_api_fold 1 --num_synthetic_per_iter 100 --num_iter 10 --priv_sampling_ratio 0.2 --max_completion_tokens 1024 --dp_epsilon 1.0 --dp_delta 1E-5 --train_batch_size 4 > temp_qwen_congressional_seed1.txt
CUDA_VISIBLE_DEVICES=0 python examples/main_text.py --seed 42 --task congressional --gen_model_name Qwen/Qwen2.5-3B-Instruct --fine_tune_model_name Qwen/Qwen2.5-3B-Instruct --target_modules q_proj v_proj --use_local_model True --lr 5e-4 --variation_api_fold 1 --num_synthetic_per_iter 100 --num_iter 10 --priv_sampling_ratio 0.2 --max_completion_tokens 1024 --dp_epsilon 1.0 --dp_delta 1E-5 --train_batch_size 4 > temp_qwen_congressional_seed42.txt

CUDA_VISIBLE_DEVICES=0 python examples/main_text.py --seed 0 --task pubmed --gen_model_name Qwen/Qwen2.5-3B-Instruct --fine_tune_model_name Qwen/Qwen2.5-3B-Instruct --target_modules q_proj v_proj --use_local_model True --lr 5e-4 --variation_api_fold 1 --num_synthetic_per_iter 100 --num_iter 10 --priv_sampling_ratio 0.2 --max_completion_tokens 1024 --dp_epsilon 1.0 --dp_delta 1E-5 --train_batch_size 4 > temp_qwen_pubmed_seed0.txt
CUDA_VISIBLE_DEVICES=0 python examples/main_text.py --seed 1 --task pubmed --gen_model_name Qwen/Qwen2.5-3B-Instruct --fine_tune_model_name Qwen/Qwen2.5-3B-Instruct --target_modules q_proj v_proj --use_local_model True --lr 5e-4 --variation_api_fold 1 --num_synthetic_per_iter 100 --num_iter 10 --priv_sampling_ratio 0.2 --max_completion_tokens 1024 --dp_epsilon 1.0 --dp_delta 1E-5 --train_batch_size 4 > temp_qwen_pubmed_seed1.txt
CUDA_VISIBLE_DEVICES=0 python examples/main_text.py --seed 42 --task pubmed --gen_model_name Qwen/Qwen2.5-3B-Instruct --fine_tune_model_name Qwen/Qwen2.5-3B-Instruct --target_modules q_proj v_proj --use_local_model True --lr 5e-4 --variation_api_fold 1 --num_synthetic_per_iter 100 --num_iter 10 --priv_sampling_ratio 0.2 --max_completion_tokens 1024 --dp_epsilon 1.0 --dp_delta 1E-5 --train_batch_size 4 > temp_qwen_pubmed_seed42.txt

# GPT-2 
CUDA_VISIBLE_DEVICES=0 python examples/main_text.py --seed 0 --task biorxiv --gen_model_name openai-community/gpt2 --fine_tune_model_name openai-community/gpt2 --target_modules c_attn c_proj --use_local_model True --lr 1e-5 --variation_api_fold 1 --num_synthetic_per_iter 100 --num_iter 10 --priv_sampling_ratio 0.2 --max_completion_tokens 256 --dp_epsilon 1.0 --dp_delta 1E-5 >> temp.txt

